export const IS_CONNECTED = 'socket/IS_CONNECTED'
export const SUBMIT_USER_ID = 'socket/SUBMIT_USER_ID'
export const SUBMIT_CURRENT_ROOM = 'socket/SUBMIT_CURRENT_ROOM'
export const CONNECTION_CREATED = 'socket/CONNECTION_CREATED'
export const SET_INVITATION = 'socket/SET_INVITATION'
export const CLEAR_INVITATION = 'socket/CLEAR_INVITATION'