export const SET_USER = 'user/SET_USERNAME'
export const SET_USER_FRIENDS = 'user/SET_FRIENDS'
export const SET_USER_FRIEND_REQUESTS = 'user/SET_FRIEND_REQUESTS'
export const NEW_USER_FRIEND_REQUEST = 'user/NEW_FRIEND_REQUEST'