export const SET_USER = 'user/SET_USERNAME'
// FRIENDS
export const SET_FRIENDS = 'user/SET_FRIENDS'
export const SET_AWAIT_FRIENDS = 'user/SET_AWAIT_FRIENDS'
export const ADD_NEW_FRIEND = 'user/ADD_NEW_FRIEND'
export const UPDATE_FRIEND_STATUS = 'user/UPDATE_FRIEND_STATUS'
export const REMOVE_FRIEND = 'user/REMOVE_FRIEND'
// FRIEND REQUEST
export const SET_FRIEND_REQUESTS = 'user/SET_FRIEND_REQUESTS'
export const ADD_NEW_FRIEND_REQUEST = 'user/ADD_NEW_FRIEND_REQUEST'
export const REMOVE_FRIEND_REQUEST = 'user/REMOVE_FRIEND_REQUEST'